### ISSUE TITLE
Benefits of fsi-open/files

### ISSUE THREAD

**Issue by pawloaka** [fsi-open/files#41]
Hi, 
1) What are the benefits of using your bundle?
I know only that it speeds up setting file fields for my entities.

2) What is the difference between your bundle and `flysystem-bundle`?

**Comment by szymach** [comment]
1. It provides agnostic interfaces for file objects (`WebFile` and `UploadedWebFile`) which can be used in various integrations, `flysystem-bundle` being just one of them. We wanted this library to be lightweight and extendable, but for now we only use the Symfony/Doctrine ORM/Flysystem combo, since it suits our needs just fine.

2. `flysystem-bundle` is purely for file operations. This package is about treating files as objects of the Web, meaning that they have some kind of creation or upload mechanism (a form, CURL call, whatever), they need to be stored somewhere and then displayed on a web page.
